### ISSUE TITLE
Docker building error

### ISSUE THREAD

**Issue by d0znpp** [ijcd/ragel_playground#5]
```
Step 7/10 : RUN bundle install
 ---> Running in 01fea8728393
/usr/local/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /app/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
	from /usr/local/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
ERROR: Service 'app' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 1

```

**Comment by ijcd** [comment]
This was a demo project for a presentation I did several years ago. I'm sure the ruby stuff needs to be updated. I'll definitely accept a patch. Thanks for the report.
